.TH PkgClip 1 "2012-01-10" 0.1.0 "Cached Packages Trimmer Utility"
.SH NAME
PkgClip \- Cached Packages Trimmer Utility
.SH SYNOPSIS
.B pkgclip
.SH DESCRIPTION
\fBPkgClip\fR is a little helper that will scan your pacman cache directories
and help you trim it a bit.
.P
Whenever \fBpacman\fR downloads packages, it saves them in a cache directory,
and never removes them. Over time, this cache can grow a lot.
.P
While \fBpacman\fR does offer options to clean your cache, they are very basic.
Its option \fB--clean\fR (\fB-c\fR) will remove packages that are no longer
installed from the cache (as well as currently unused sync databases. Note that
\fBPkgClip\fR does not touch databases, only packages.), or remove all packages
if you specify it twice.
.P
\fBPkgClip\fR aims at giving you a little more options. To do so, it will
classify all packages into different "groups" (also called "reasons", as in
reason for the recommended action), each group having a recommendation (Keep or
Remove), used as default choice.
.P
You will of course be able to then review it all, and decides which packages
shall be removed, and which shall not.

.SH REASONS (GROUPS)
For each package, PkgClip will check whether or not it is installed on the system.
The test will determine whether this version of the package is installed, or another
one.
.P
\fBMore recent than installed version\fR - Recommendation: \fBKeep\fR
.RS 4
A package of a version more recent than the one currently installed.
.RE
.P
\fBInstalled on system\fR - Recommendation: \fBKeep\fR
.RS 4
A package currently installed.
.RE
.P
\fBRecent older version\fR - Recommendation: \fBKeep\fR
.RS 4
A package of an older version than the one currently installed. If option
\fBRemove older package releases\fR is enabled, this will not include packages
of the same version but with a different package release number (pkgrel).
.RE
.P
\fBOlder version\fR - Recommendation: \fBRemove\fR
.RS 4
A package of an older version than the one currently installed, and older than
as many packages of older version as specified (see \fBPREFERENCES\fR below)
have been found.
.RE
.P
\fBPrevious package release\fR - Recommendation: \fBRemove\fR
.RS 4
A package of the same version than the one currently installed, but with an older
package release number (pkgrel). Only if option \fBRemove older package
releases\fR is enabled.
.RE
.P
\fBPackage not installed on system (any version)\fR - Recommendation: \fBRemove\fR
.RS 4
A package for which no version is currently installed.
.RE

.SH PREFERENCES
Preferences are available through the menu \fIEdit|Preferences\fR (Note: you can
pop up the menu \fIEdit\fR by right-clicking on the list). When pressing "OK"
they will be automatically applied, then saved to a file \fBpkgclip.conf\fR
located inside a folder \fB.config\fR in your HOME directory.
.P
\fBLocation of pacman.conf\fR
.RS 4
The directory where your \fBpacman.conf\fR file is located. PkgClip parses this
file in order to use \fBlibalpm\fR and access your local database, as well as
determine your cache directories.
.RE
.P
\fBNumber of old versions to keep\fR
.RS 4
How many versions of older than installed to keep. The Nth more recent versions
will be classified as \fBRecent older version\fR, older ones will fall under
\fBOlder version\fR.
.P
If you do not want to keep any older version, simply specify 0 (zero).
.P
Note that if option \fBRemove older package releases\fR is enabled, this will
only refer to packages for older versions, not same version number but with an
older package release number.
.RE
.P
\fBRemove older package releases\fR
.RS 4
When enabled, PkgClip will classify differently packages of older versions, and
packages of the same version as currently installed, but with an older package
release, the later being marked for removal (\fBPrevious package release\fR).
.P
All packages have similar names, such as: package-name-1.2.3-4
.P
Here, the version number is 1.2.3, while 4 is the package release (pkgrel).
.P
For example, with packages foobar-1.3-3, foobar-1.3-2 and foobar-1.2-4 and
foobar-1.3-3 being installed, this option will have foobar-1.3-2 marked for
removal while keeping foobar-1.2-4; while without it it would be the other
way around (assuming you keep one older version).
.RE
.P
\fBUse sane sort indicator\fR
.RS 4
Makes it so that when sort descendingly, the arrow points down... as it should.
.RE
.P
\fBDo not load packages on start\fR
.RS 4
By default PkgClip automatically scans your cache directories and loads packages
upon start. Should you not want that to happen, this will help you achieve your
goal.
.RE
.P

.SH REMOVING PACKAGES
Removing packages is not something you should be able to do as a user, since
all those files belong to root. In order to remove those files (without the
need to be run as root), PkgClip rely on \fBPolicyKit\fR.
.P
When you're ready and want PkgClip to remove all marked (checked) packages,
simply click the button. After a final confirmation, you should see your
\fBPolicyKit\fR agent show up and ask for your password. Once validated, files
will be removed as expected.
.P
Note that this obviously depends on your configuration. For instance if you
do not have a PolicyKit agent installed/running, PkgClip will simply fail since
you cannot be authentificated.

.SH CHANGE RECOMMENDATIONS
If you are not pleased with the default recommendations for each reasons/groups,
you can change them.
.P
To do so, you will need to manually edit the configuration file. Note that while
no GUI exists for those options, they will obviously be preserved when PkgClip
saves its preferences.
.P
Also note that the different labels (e.g. option names) will \fBNOT\fR be
updated to reflect any changes you might have done. That is, option \fBRemove
older package releases\fR will continue to be called that, even if you changed
the default recommendation from Remove to Keep (and thus, the option would
really mean \fBKeep older package releases\fR).
.P
To change a recommendation, simply add into your \fBpkgclip.conf\fR one of
the following key, with a value of either \fBKeep\fR or \fBRemove\fR
(e.g. RecommForNewerThanInstalled = Remove)
.P
.RS 4
RecommForNewerThanInstalled

RecommForInstalled

RecommForOlderVersion

RecommForAlreadyOlderVersion

RecommForOlderPkgrel

RecommForPkgNotInstalled
.RE
.P

.SH BUGS
They're probably crawling somewhere in there... if you happen to catch one (or
more), report it and I'll do my best to squash it.
.SH REPOSITORY
You can find the latest source code of \fBPkgClip\fR as well as report bugs
and/or feature suggestions on its BitBucket repository available at
.I https://bitbucket.org/jjacky/pkgclip
.SH AUTHORS
Olivier Brunel <i.am.jack.mail AT gmail DOT com>

Pacman Development Team <pacman-dev AT archlinux DOT org>
.SH ARTWORK
Icon by Hylke Bons in Discovery Icon Theme, released under CC BY-SA 3.0
